bot:
    # The bot token from https://discord.com/developers/applications
    token: "add-your-token-here"

    # Your Discord server's ID.
    server-id: 000000000000000000

    # Prefix for discord commands.
    prefix: "+"

    # Channel to post the bot status messages in.
    status-channels: [ 000000000000000000, 111111111111111111 ]

    # The channels where bot commands can be used.
    command-channels: [ 000000000000000000, 111111111111111111 ]

    # Decides what messages are shown in console
    # Possible values are: Critical, Error, Warning, Information, Debug.
    log-level: "Information"

    # Sets the type of activity for the bot to display in its presence status when the server is offline
    # Possible values are: Playing, Streaming, ListeningTo, Watching, Competing
    presence-type: "Watching"

    # Sets the activity text shown in the bot's status.
    presence-text: "for server startup..."

plugin:
    # Host to listen on, localhost by default. Try changing this to "0.0.0.0" (all addresses available) if the plugin isn't able to connect, some windows setups don't seem to work with a set address to listen on.
    # In case you want server to listen on something other than "127.0.0.1", make sure your firewall rules are correct so any outside connections are blocked to the port.
    address: "127.0.0.1"

    # Port to listen on, this has to be the same as the "bot port" in the plugin config and all bots you run have to have different ports or they will clash.
    port: 8888

# Set permissions for discord roles here. (Use 0 to allow anyone to use the command)
# The dictionary defines the role ids and the commands they have access to.
# If a role has access to "server aabbcc" all users with that role will be able 
# to use the command "+server aabbcc" but also any command starting with it such as "+server aabbccdd"
permissions:
    000000000000000000: # An everyone role example
        - list
    111111111111111111: # A donator role example
        - vs_whitelist
        - syncrole
        - unsyncrole
    222222222222222222: # A moderator example
        - syncrole
        - ban
        - unban
        - kick
        - kickall
        - server roundrestart
        - server hidetag
        - server showtag
        - server vs_reload
        - server vs_enable
        - server vs_disable
        - server scpd_reload
        - server scpd_unsync