
############# SCPDiscord configuration file #############


# Connection settings
bot:
    ip: "127.0.0.1"
    port: 8888

settings:
    # The language is the same as the name of the language file you want to use.
    # Included language files: english (default), russian, french, englishemote
    language: "english"
    # Whether or not to show this server's player count in the bot's activity.
    # Set to false to disable.
    playercount: true
    # The message timestamp, see syntax guide here: https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/8kb3ddd4(v=vs.85)
    # Set to "" to disable.
    timestamp: "HH:mm:ss"
    # Whether or not the plugin should send more detailed console messages
    # Set to true to turn on.
    verbose: false
    # Whether or not the plugin should send debug information in the console
    # Set to true to turn on.
    debug: false
    # Turns on the config validation which shows the values after they have been read by the plugin so you can see they are correct
    configvalidation: false

# Name your channels here, this name is used in the channels section below. The left value is a name of your choice and the right is a channel id you want it to represent.
aliases: ["default":"add-role-id-here","staff":"add-role-id-here"]

# Using the channel aliases above you can direct events to different channels here
# Set to [] to disable an event.
channels:
    # Bot messages
    statusmessages: [ "default", "staff" ]

    # Channel topic updater
    topic: [ "default", "staff" ]

    # Round events
    onroundstart: [ "default", "staff" ]
    onconnect: [ "default", "staff" ]
    ondisconnect: [ "default", "staff" ]
    oncheckroundend: []
    onroundend: [ "default", "staff" ]
    onwaitingforplayers: [ "default" ]
    onroundrestart: [ "default", "staff" ]
    onsetservername: []
    onscenechanged: []

    # Environment events
    onscp914activate: []
    onstartcountdown: 
        initiated: [ "default" ]
        resumed: [ "default" ]
    onstopcountdown: [ "default" ]
    ondetonate: [ "default" ]
    ondecontaminate: [ "default" ]
    
    # Player events
    onplayerhurt:
        default: []
        friendlyfire: []
        noattacker: []
    onplayerdie: 
        default: [ "default" ]
        friendlyfire: [ "default", "staff" ]
        noattacker: [ "default" ]
    onplayerpickupitem: []
    onplayerdropitem: []
    onplayerjoin: [ "default", "staff" ]
    onnicknameset: [ "default", "staff" ]
    onassignteam: []
    onsetrole: []
    oncheckescape:
        allowed: [ "default" ]
        denied: []
    onspawn: [ "staff" ]
    ondooraccess:
        allowed: []
        denied: []
    onintercom: []
    onintercomcooldowncheck: []
    onpocketdimensionexit: [ "default" ]
    onpocketdimensionenter: [ "default" ]
    onpocketdimensiondie: []
    onthrowgrenade: [ "default", "staff" ]
    onplayerinfected: [ "default" ]
    onspawnragdoll: []
    onlure: [ "default" ]
    oncontain106: [ "default" ]
    onmedkituse: [ "default" ]
    onshoot:
        default: []
        friendlyfire: []
        notarget: []
    on106createportal: []
    on106teleport: []
    onelevatoruse: []
    onhandcuff:
        default: [ "default" ]
        nootherplayer: [ "default" ]
    onplayertriggertesla:
        default: []
        ignore: []
    onscp914changeknob: []
    
    # Admin events
    onadminquery: [ "staff" ]
    onauthcheck: [ "staff" ]
    onban: 
        admin: [ "default", "staff" ]
        console: [ "default", "staff" ]

    # Team events
    ondecideteamrespawnqueue: []
    onsetrolemaxhp: []
    onteamrespawn:
        mtf: []
        ci: [ "default" ]
    onsetscpconfig: []
    onsetntfunitname: [ "default" ]